services:
  post:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3001"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: hello
    ports:
      - "5432:5432"